name: "Aspect issue"
description: >
  Optional sub-division of an Objective, that is composed of multiple Task issues. Can be linked to a PR (if contained Task issues are not linked).
labels: ["Aspect"]
body:
- type: markdown
  attributes: 
    value: |
      * If you are going to work on the Aspect, assign it to yourself
      * After creating the Aspect issue, create Task issues as sub-issues
        * You can also use a task list in the description field as a scratchpad, and then convert the task list items to sub-issues
- type: textarea
  attributes:
    label: "Description"
    description: "Description of the Aspect (can be empty)"
    placeholder: >
      Write here something about the aspect if it is not clear from the title.
